import { useRef } from 'react';
import { formatDate } from '../lib/dateUtils';

/**
 * BillPreviewModal — Renders a printable bill / challan preview for any transaction.
 *
 * Props:
 *  - entry        {Object}   The transaction object (date, bill, party, type, items, remark, godown, etc.)
 *  - module       {string}   'Sale' | 'Purchase' | 'DCWR OUT' | 'DCWR IN' | 'Transfer' | 'Adjustment'
 *  - products     {Object}   Map of productId → { code, name, category }
 *  - onClose      {Function} Close handler
 */
export default function BillPreviewModal({ entry, module, products, onClose }) {
  const printRef = useRef(null);

  if (!entry) return null;

  const items = entry.items || {};
  const itemEntries = Object.entries(items).filter(([, qty]) => qty > 0);
  const totalQty = itemEntries.reduce((sum, [, qty]) => sum + qty, 0);

  const billNo = entry.bill || entry.challan || entry.refNo || '—';
  const partyName = entry.party || entry.fromGodown || '—';
  const godown = entry.godown || (entry.fromGodown ? `${entry.fromGodown} → ${entry.toGodown}` : '—');
  const entryType = entry.type || module;
  const remark = entry.remark || entry.reason || '—';

  const handlePrint = () => {
    const printContent = printRef.current;
    if (!printContent) return;
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${module} — ${billNo}</title>
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"/>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Inter', sans-serif; color: #222; padding: 32px; background: #fff; }
          .bill-header { display: flex; align-items: center; gap: 16px; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #131313; }
          .bill-logo svg { width: 36px; height: 36px; }
          .bill-title { font-family: 'Space Grotesk', sans-serif; }
          .bill-title h1 { font-size: 22px; font-weight: 700; }
          .bill-title p { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 2px; }
          .bill-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 24px; margin-bottom: 24px; font-size: 13px; }
          .bill-meta dt { font-weight: 600; color: #888; text-transform: uppercase; font-size: 10px; letter-spacing: 1px; }
          .bill-meta dd { font-weight: 600; color: #111; margin-bottom: 8px; }
          .bill-module-badge { display: inline-block; padding: 4px 16px; border-radius: 999px; font-size: 11px; font-weight: 700; background: #131313; color: #ffb1c3; margin-bottom: 16px; text-transform: uppercase; letter-spacing: 1.5px; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
          th { background: #131313; color: #fff; padding: 8px 12px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; }
          td { padding: 8px 12px; border-bottom: 1px solid #e5e5e5; font-size: 13px; }
          tr:nth-child(even) td { background: #fafafa; }
          .bill-total { text-align: right; font-size: 16px; font-weight: 700; font-family: 'Space Grotesk', sans-serif; margin-top: 8px; }
          .bill-remark { margin-top: 16px; padding: 12px; background: #f8f8f8; border-radius: 8px; font-size: 12px; color: #555; }
          .bill-footer { margin-top: 32px; text-align: center; font-size: 10px; color: #aaa; border-top: 1px solid #eee; padding-top: 12px; }
          @media print { body { padding: 16px; } }
        </style>
      </head>
      <body>
        ${printContent.innerHTML}
        <div class="bill-footer">Generated by Magnus Drive — ${new Date().toLocaleString('en-IN')}</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 300);
  };

  return (
    <div
      className="fixed inset-0 z-[200] flex items-center justify-center p-4"
      style={{ background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(12px)' }}
      onClick={onClose}
    >
      <div
        className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl shadow-2xl"
        style={{ background: 'var(--paper)' }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Action Bar */}
        <div className="sticky top-0 z-10 flex items-center justify-between px-6 py-4 rounded-t-2xl" style={{ background: 'var(--soft)', borderBottom: '1px solid var(--line)' }}>
          <span className="text-sm font-bold uppercase tracking-widest" style={{ color: 'var(--muted)' }}>Bill Preview</span>
          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="px-5 py-2 rounded-full text-xs font-bold text-white transition-all hover:scale-105"
              style={{ background: 'linear-gradient(135deg, #ff4b89, #ffb1c3)' }}
            >
              🖨 Print
            </button>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-full flex items-center justify-center text-lg transition-all hover:bg-white/10"
              style={{ color: 'var(--muted)' }}
            >
              ✕
            </button>
          </div>
        </div>

        {/* Printable Content */}
        <div ref={printRef} className="p-6 space-y-5">
          {/* Header with Logo */}
          <div className="bill-header" style={{ display: 'flex', alignItems: 'center', gap: '16px', paddingBottom: '16px', borderBottom: '2px solid var(--line)' }}>
            <div className="bill-logo">
              <svg width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4 20V4L12 12" stroke="#ffffff" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/>
                <path d="M12 12L20 4V20" stroke="#ff4b89" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
            <div className="bill-title">
              <h1 style={{ fontFamily: 'var(--font-display)', fontSize: '22px', fontWeight: 700, color: 'var(--ink)' }}>MAGNUS AGENCIES</h1>
              <p style={{ fontSize: '11px', color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '2px' }}>Inventory Management System</p>
            </div>
          </div>

          {/* Module Badge */}
          <div>
            <span className="px-4 py-1.5 rounded-full text-[11px] font-bold uppercase tracking-widest" style={{ background: 'var(--soft)', color: 'var(--teal3)', border: '1px solid var(--line)' }}>
              {module}
            </span>
          </div>

          {/* Metadata Grid */}
          <div className="grid grid-cols-2 gap-x-6 gap-y-3">
            <div>
              <div className="text-[10px] font-bold uppercase tracking-widest mb-0.5" style={{ color: 'var(--muted)' }}>Date</div>
              <div className="text-sm font-bold" style={{ color: 'var(--ink)' }}>{formatDate(entry.date)}</div>
            </div>
            <div>
              <div className="text-[10px] font-bold uppercase tracking-widest mb-0.5" style={{ color: 'var(--muted)' }}>Bill / Ref No.</div>
              <div className="text-sm font-bold font-mono" style={{ color: 'var(--ink)' }}>{billNo}</div>
            </div>
            <div>
              <div className="text-[10px] font-bold uppercase tracking-widest mb-0.5" style={{ color: 'var(--muted)' }}>Party</div>
              <div className="text-sm font-bold" style={{ color: 'var(--ink)' }}>{partyName}</div>
            </div>
            <div>
              <div className="text-[10px] font-bold uppercase tracking-widest mb-0.5" style={{ color: 'var(--muted)' }}>Godown</div>
              <div className="text-sm font-bold" style={{ color: 'var(--ink)' }}>{godown}</div>
            </div>
            <div>
              <div className="text-[10px] font-bold uppercase tracking-widest mb-0.5" style={{ color: 'var(--muted)' }}>Type</div>
              <div className="text-sm font-bold" style={{ color: 'var(--teal3)' }}>{entryType}</div>
            </div>
          </div>

          {/* Items Table */}
          <div className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--line)' }}>
            <table className="w-full text-sm" style={{ borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: 'var(--soft)' }}>
                  <th className="px-4 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest" style={{ color: 'var(--muted)' }}>#</th>
                  <th className="px-4 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest" style={{ color: 'var(--muted)' }}>Product Code</th>
                  <th className="px-4 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest" style={{ color: 'var(--muted)' }}>Name</th>
                  <th className="px-4 py-2.5 text-right text-[10px] font-bold uppercase tracking-widest" style={{ color: 'var(--muted)' }}>Qty</th>
                </tr>
              </thead>
              <tbody>
                {itemEntries.length === 0 ? (
                  <tr><td colSpan={4} className="text-center py-6 text-xs" style={{ color: 'var(--muted)' }}>No items</td></tr>
                ) : (
                  itemEntries.map(([id, qty], i) => {
                    const p = products[id];
                    return (
                      <tr key={id} className="transition-colors" style={{ borderBottom: '1px solid var(--line)' }}>
                        <td className="px-4 py-2" style={{ color: 'var(--muted)' }}>{i + 1}</td>
                        <td className="px-4 py-2 font-mono font-bold" style={{ color: 'var(--teal3)' }}>{p?.code || id}</td>
                        <td className="px-4 py-2" style={{ color: 'var(--ink)' }}>{p?.name || '—'}</td>
                        <td className="px-4 py-2 text-right font-bold" style={{ color: 'var(--ink)' }}>{qty}</td>
                      </tr>
                    );
                  })
                )}
              </tbody>
              <tfoot>
                <tr style={{ background: 'var(--soft)' }}>
                  <td colSpan={3} className="px-4 py-2.5 text-right text-xs font-bold uppercase tracking-widest" style={{ color: 'var(--muted)' }}>Total</td>
                  <td className="px-4 py-2.5 text-right font-bold text-lg" style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}>{totalQty}</td>
                </tr>
              </tfoot>
            </table>
          </div>

          {/* Scrap Items (Sales only) */}
          {entry.scrapProvided && entry.scrapItems && Object.keys(entry.scrapItems).length > 0 && (
            <div>
              <div className="text-[10px] font-bold uppercase tracking-widest mb-2" style={{ color: 'var(--muted)' }}>♻️ Scrap Items Received</div>
              <div className="rounded-xl overflow-hidden" style={{ border: '1px solid var(--line)' }}>
                <table className="w-full text-sm" style={{ borderCollapse: 'collapse' }}>
                  <thead>
                    <tr style={{ background: 'var(--soft)' }}>
                      <th className="px-4 py-2 text-left text-[10px] font-bold uppercase" style={{ color: 'var(--muted)' }}>Product</th>
                      <th className="px-4 py-2 text-right text-[10px] font-bold uppercase" style={{ color: 'var(--muted)' }}>Qty</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(entry.scrapItems).filter(([, q]) => q > 0).map(([id, qty]) => (
                      <tr key={id} style={{ borderBottom: '1px solid var(--line)' }}>
                        <td className="px-4 py-2 font-mono font-bold" style={{ color: 'var(--ink)' }}>{products[id]?.code || id}</td>
                        <td className="px-4 py-2 text-right font-bold" style={{ color: 'var(--ink)' }}>{qty}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Remarks */}
          {remark && remark !== '—' && (
            <div className="p-3 rounded-xl" style={{ background: 'var(--soft)' }}>
              <div className="text-[10px] font-bold uppercase tracking-widest mb-1" style={{ color: 'var(--muted)' }}>Remarks</div>
              <div className="text-xs" style={{ color: 'var(--ink)' }}>{remark}</div>
            </div>
          )}

          {/* Footer */}
          <div className="text-center text-[10px] pt-4" style={{ color: 'var(--muted)', borderTop: '1px solid var(--line)' }}>
            Generated by Magnus Drive — {new Date().toLocaleString('en-IN')}
          </div>
        </div>
      </div>
    </div>
  );
}
